const movieData = [
  {
    phim_id: 1,
    ten_phim: "Avengers: Endgame",
    mo_ta: "Biệt đội Avengers tập hợp để đảo ngược hành động của Thanos và khôi phục vũ trụ.",
    thoi_luong: 181,
    the_loai: ["Hành động", "Khoa học viễn tưởng"],
    dien_vien: ["Robert Downey Jr.", "Chris Evans"],
    dao_dien: "Anthony Russo, Joe Russo",
    quoc_gia: "Mỹ",
    nam_phat_hanh: 2019,
    image: "https://brandsketer.com/upload/category/chien-dich-marketing-khung-cua-avengers-endgame-va-cac-thuong-hieu-lien-ket-1563158033.jpg",
    trailer: "https://www.youtube.com/watch?v=TcMBFSGVi1c",
    nhan_phim: "PG-13",
    ngay_cong_chieu: "2025-07-01",
    ngay_ket_thuc: "2025-08-01",
    trang_thai: "dang_chieu",
    lphim_id: 1,
    admin_id: 1
  },
  {
    phim_id: 4,
    ten_phim: "Parasite",
    mo_ta: "Gia đình nghèo tìm cách thâm nhập vào gia đình giàu có bằng các chiêu trò thông minh.",
    thoi_luong: 132,
    the_loai: ["Tâm lý", "Kịch tính"],
    dien_vien: ["Song Kang-ho", "Choi Woo-shik"],
    dao_dien: "Bong Joon-ho",
    quoc_gia: "Hàn Quốc",
    nam_phat_hanh: 2019,
    image: "https://upload.wikimedia.org/wikipedia/en/5/53/Parasite_%282019_film%29.png",
    trailer: "https://www.youtube.com/watch?v=SEUXfv87Wpk",
    nhan_phim: "T18",
    ngay_cong_chieu: "2025-06-15",
    ngay_ket_thuc: "2025-07-15",
    trang_thai: "dang_chieu",
    lphim_id: 2,
    admin_id: 2
  },
  {
    phim_id: 5,
    ten_phim: "Interstellar",
    mo_ta: "Một nhóm phi hành gia đi xuyên qua hố đen để tìm kiếm hành tinh mới cho nhân loại.",
    thoi_luong: 169,
    the_loai: ["Khoa học viễn tưởng", "Phiêu lưu"],
    dien_vien: ["Matthew McConaughey", "Anne Hathaway"],
    dao_dien: "Christopher Nolan",
    quoc_gia: "Mỹ",
    nam_phat_hanh: 2014,
    image: "https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg",
    trailer: "https://www.youtube.com/watch?v=zSWdZVtXT7E",
    nhan_phim: "PG-13",
    ngay_cong_chieu: "2025-07-10",
    ngay_ket_thuc: "2025-08-10",
    trang_thai: "sap_chieu",
    lphim_id: 3,
    admin_id: 3
  },
  {
    phim_id: 20,
    ten_phim: "Kung Fu Panda 5",
    mo_ta: "Po trở lại để bảo vệ thung lũng hòa bình.",
    thoi_luong: 95,
    the_loai: ["Hoạt hình", "Hài", "Phiêu lưu"],
    dien_vien: ["Jack Black", "Awkwafina"],
    dao_dien: "Mike Mitchell",
    quoc_gia: "Mỹ",
    nam_phat_hanh: 2025,
    image: "https://thegioiblu-ray.com/resources/200ceb26807d6bf99fd6f4f0d1ca54d4/1-HD%20LE%204/3356.jpg",
    trailer: "https://youtube.com",
    nhan_phim: "T13",
    ngay_cong_chieu: "2025-06-01",
    ngay_ket_thuc: "2025-07-01",
    trang_thai: "het_chieu",
    lphim_id: 4,
    admin_id: 1
  }
];

export default movieData;
